// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xworhgopytabzldmvkry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3b3JoZ29weXRhYnpsZG12a3J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwNDMxNDcsImV4cCI6MjA3ODYxOTE0N30.b7xPg0Qm2nkUUPAEVpJioeDwHMEeS9_0LZcuGBR0H3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});